name: "imyong"
description: imyong

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  http: ^0.13.4
  flutter:
    sdk: flutter

  tnd_core:
    git:
      url: "https://git.technolda.com/Technolda/tnd_core.git"
      ref: v1-migration
  tnd_pkg_widget:
    git:
      url: "https://git.technolda.com/Technolda/tnd_pkg_widget.git"
      ref: v1-migration
  tnd_pkg_repository:
    git:
      url: "https://git.technolda.com/Technolda/tnd_pkg_repository.git"
      ref: v1-migration

  cupertino_icons: ^1.0.2
  file_picker: ^3.0.4
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
