name: "imyong"
description: imyong

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  http: ^0.13.4
  flutter:
    sdk: flutter

  tnd_core:
    git:
      url: "https://git.technolda.com/Technolda/tnd_core.git"
      ref: v1.5
  tnd_pkg_widget:
    git:
      url: "https://git.technolda.com/Technolda/tnd_pkg_widget.git"
      ref: v1.5
  tnd_pkg_repository:
    git:
      url: "https://git.technolda.com/Technolda/tnd_pkg_repository.git"
      ref: v1.5

  hive: 2.0.4
  hive_flutter: 1.1.0
  cupertino_icons: ^1.0.2
  file_picker: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
